[tool.poetry]
name = "django_inha"
version = "0.1.0"
description = ""
authors = ["seokmin <soos3121@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
